### ISSUE TITLE
TypeError: Cannot handle this data type: (1, 1, 3), <u2

### ISSUE THREAD

**Issue by NeuroLord** [PKU-YuanGroup/Envision3D#2]
When preprocessing the input image, I get a PIL library error about the impossibility of converting numbers from one type to another (if I understand the principle of the program correctly). 
I tried to work on both Windows 10 and WSL 2, but the result is the same. What am I doing wrong?

**Full traceback:**
  ```
python process_img.py example_imgs/bog.png processed_imgs/ --size 256 --recenter
[INFO] loading image example_imgs/bog.png...
example_imgs/bog.png
[INFO] normal estimation...
F:\Programs\Anaconda\envs\envision3d\lib\site-packages\timm\models\_factory.py:117: UserWarning: Mapping deprecated model name vit_base_resnet50_384 to current vit_base_r50_s16_384.orig_in21k_ft_in1k.
  model = create_fn(
Traceback (most recent call last):
  File "F:\Programs\Anaconda\envs\envision3d\lib\site-packages\PIL\Image.py", line 3130, in fromarray
    mode, rawmode = _fromarray_typemap[typekey]
KeyError: ((1, 1, 3), '<u2')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "K:\programs\Envision3d\process_img.py", line 273, in <module>
    preprocess_single_image(opt.path, opt)
  File "K:\programs\Envision3d\process_img.py", line 161, in preprocess_single_image
    normal = dpt_normal_model(image)[0].transpose(1, 2, 0)
  File "F:\Programs\Anaconda\envs\envision3d\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "K:\programs\Envision3d\process_img.py", line 100, in __call__
    image = Image.fromarray(image)
  File "F:\Programs\Anaconda\envs\envision3d\lib\site-packages\PIL\Image.py", line 3134, in fromarray
    raise TypeError(msg) from e
TypeError: Cannot handle this data type: (1, 1, 3), <u2
```

**Comment by NeuroLord** [comment]
Fixed this problem by replacing all lines `image = Image.fromarray(image)` in `process_img.py` with `image = Image.fromarray(image.astype(np.uint8))`
