### ISSUE TITLE
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:

### ISSUE THREAD

**Issue by throb081** [PKU-YuanGroup/Envision3D#5]
你好，我在运行阶段一的代码的时候报出来这个警告，请问代码中的注意力部分是不是精读太高了，还是我这边的运行环境和您的不太一样，这个代码是不是需要A100才能跑起来呢？想了解一下您在跑这个代码的时候环境是怎么样的。
Traceback (most recent call last):
  File "/home/yw/yw2/LZH/PaperCode/Envision3D/Envision3D-main/gen_s1.py", line 230, in <module>
    main(cfg)
  File "/home/yw/yw2/LZH/PaperCode/Envision3D/Envision3D-main/gen_s1.py", line 177, in main
    pipeline = load_envision3d_pipeline(cfg)
  File "/home/yw/yw2/LZH/PaperCode/Envision3D/Envision3D-main/gen_s1.py", line 161, in load_envision3d_pipeline
    pipeline.unet.enable_xformers_memory_efficient_attention()
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 299, in enable_xformers_memory_efficient_attention
    self.set_use_memory_efficient_attention_xformers(True, attention_op)
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 263, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 259, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 259, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 259, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 256, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 263, in set_use_memory_efficient_attention_xformers
    fn_recursive_set_mem_eff(module)
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 259, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 259, in fn_recursive_set_mem_eff
    fn_recursive_set_mem_eff(child)
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/diffusers/models/modeling_utils.py", line 256, in fn_recursive_set_mem_eff
    module.set_use_memory_efficient_attention_xformers(valid, attention_op)
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 268, in set_use_memory_efficient_attention_xformers
    raise e
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/diffusers/models/attention_processor.py", line 262, in set_use_memory_efficient_attention_xformers
    _ = xformers.ops.memory_efficient_attention(
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 197, in memory_efficient_attention
    return _memory_efficient_attention(
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 293, in _memory_efficient_attention
    return _memory_efficient_attention_forward(
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/xformers/ops/fmha/__init__.py", line 309, in _memory_efficient_attention_forward
    op = _dispatch_fw(inp)
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 95, in _dispatch_fw
    return _run_priority_list(
  File "/home/yw/anaconda3/envs/InstantMesh/lib/python3.10/site-packages/xformers/ops/fmha/dispatch.py", line 70, in _run_priority_list
    raise NotImplementedError(msg)
NotImplementedError: No operator found for `memory_efficient_attention_forward` with inputs:
     query       : shape=(1, 2, 1, 40) (torch.float32)
     key         : shape=(1, 2, 1, 40) (torch.float32)
     value       : shape=(1, 2, 1, 40) (torch.float32)
     attn_bias   : <class 'NoneType'>
     p           : 0.0
`flshattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
`tritonflashattF` is not supported because:
    xFormers wasn't build with CUDA support
    dtype=torch.float32 (supported: {torch.float16, torch.bfloat16})
    requires A100 GPU
`cutlassF` is not supported because:
    xFormers wasn't build with CUDA support
`smallkF` is not supported because:
    xFormers wasn't build with CUDA support
    max(query.shape[-1] != value.shape[-1]) > 32
    unsupported embed per head: 40

**Comment by Pang-Yatian** [comment]
We cannot reproduce this error on A100. I think you need to ensure the environment is aligned with ours as provided in req.txt. One issue might be your CUDA is not installed correctly or Xformers is not built with CUDA support.
